import { trackSelfDescribingEvent, CommonEventProperties, SelfDescribingJson } from '@snowplow/browser-tracker';
// Automatically generated by Snowtype

/**
 * Event defining the Add to Cart action
 */
export type AddToCart = {
    /**
     * name of item/product abandoned
     */
    name: string;
    /**
     * The price of the product at the time it was added to the cart
     */
    price?: number;
    /**
     * The unique identifier of the product added to the cart
     */
    productId: string;
    /**
     * The quantity of the product added to the cart
     */
    quantity?: number;
}

/**
 * Checkout Started event, with cart data.
 */
export type CheckoutStarted = {
    /**
     * The Cart ID.
     */
    cart_id: string;
}

/**
 * product entity
 */
export type EcommerceProduct = {
    /**
     * The brand of the product.
     */
    brand?: null | string;
    /**
     * The category the product belongs to. Use a consistent separator to express multiple
     * levels. E.g. Woman/Shoes/Sneakers
     */
    category: string;
    /**
     * Identifier/Name/Url for the creative presented on a list or product view.
     */
    creative_id?: null | string;
    /**
     * The currency in which the product is being priced (ISO 4217).
     */
    currency: string;
    /**
     * The SKU or product ID.
     */
    id: string;
    /**
     * The inventory status of the product E.g. in stock, out of stock, preorder, backorder.
     */
    inventory_status?: null | string;
    /**
     * The list or recommended retail price of a product.
     */
    list_price?: number | null;
    /**
     * The name or title of the product.
     */
    name?: null | string;
    /**
     * The position the product was presented in a list of products E.g. search results, product
     * list page.
     */
    position?: number | null;
    /**
     * The price of the product at the current time.
     */
    price: number;
    /**
     * The quantity of the product taking part in the ecommerce action.
     */
    quantity?: number | null;
    /**
     * The size of the product.
     */
    size?: null | string;
    /**
     * The variant of the product.
     */
    variant?: null | string;
    [property: string]: any;
}

/**
 * Properties of a product removed from cart.
 */
export type RemoveFromCart = {
    /**
     * The product name.
     */
    name: string;
    /**
     * The price when the product was removed.
     */
    price?: number | null;
    /**
     * The product ID.
     */
    productId: string;
    /**
     * The quantity removed.
     */
    quantity?: number | null;
}

/**
 * Creates a Snowplow Event Specification entity.
 */
export function createEventSpecification(eventSpecification: EventSpecification){
    return {
        schema:
            'iglu:com.snowplowanalytics.snowplow/event_specification/jsonschema/1-0-3',
        data: eventSpecification,
    }
}

/**
 * Automatically attached context for event specifications
 */
interface EventSpecification {
    id: string;
    name: string;
    data_product_id: string;
    data_product_name: string;
    data_product_domain: string;
}

type ContextsOrTimestamp<T = any> = Omit<CommonEventProperties<T>, 'context'> & { context?: SelfDescribingJson<T>[] | null | undefined }
/**
 * Track a Snowplow event for AddToCart.
 * Event defining the Add to Cart action
 */
export function trackAddToCart<T extends {} = any>(addToCart: AddToCart & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = addToCart;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.snowplowanalytics.console/add_to_cart/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow AddToCart entity.
 */
export function createAddToCart(addToCart: AddToCart){
    return {
        schema: 'iglu:com.snowplowanalytics.console/add_to_cart/jsonschema/1-0-0',
        data: addToCart
    }
}
/**
 * Track a Snowplow event for CheckoutStarted.
 * Checkout Started event, with cart data.
 */
export function trackCheckoutStarted<T extends {} = any>(checkoutStarted: CheckoutStarted & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = checkoutStarted;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosnumismatics/checkout_started/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow CheckoutStarted entity.
 */
export function createCheckoutStarted(checkoutStarted: CheckoutStarted){
    return {
        schema: 'iglu:com.leosnumismatics/checkout_started/jsonschema/1-0-0',
        data: checkoutStarted
    }
}
/**
 * Track a Snowplow event for EcommerceProduct.
 * product entity
 */
export function trackEcommerceProduct<T extends {} = any>(ecommerceProduct: EcommerceProduct & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = ecommerceProduct;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.snplow.sales.aws/ecommerce_product/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow EcommerceProduct entity.
 */
export function createEcommerceProduct(ecommerceProduct: EcommerceProduct){
    return {
        schema: 'iglu:com.snplow.sales.aws/ecommerce_product/jsonschema/1-0-0',
        data: ecommerceProduct
    }
}
/**
 * Track a Snowplow event for RemoveFromCart.
 * Properties of a product removed from cart.
 */
export function trackRemoveFromCart<T extends {} = any>(removeFromCart: RemoveFromCart & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = removeFromCart;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosnumismatics/remove_from_cart/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow RemoveFromCart entity.
 */
export function createRemoveFromCart(removeFromCart: RemoveFromCart){
    return {
        schema: 'iglu:com.leosnumismatics/remove_from_cart/jsonschema/1-0-0',
        data: removeFromCart
    }
}

/**
 * Tracks a ProductAddedToCart event specification.
 * ID: 1b8b1956-a2e0-428e-96b5-2d8e0818ba6d
 */
export function trackProductAddedToCartSpec(productAddedToCart: AddToCart & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '1b8b1956-a2e0-428e-96b5-2d8e0818ba6d',
        name: 'Product Added to Cart',
        data_product_id: 'eb003f2a-9b7b-46cf-ad7b-b8f2ee52bef9',
        data_product_name: 'Leo&#x27;s Numismatics Data Product',
        data_product_domain: 'Sales'
    });

    const context = Array.isArray(productAddedToCart.context)
        ? [...productAddedToCart.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedProductAddedToCart = {
        ...productAddedToCart,
        context,
    };

    trackAddToCart<Record<string, unknown> | EventSpecification>(modifiedProductAddedToCart, trackers);
}
/**
 * @deprecated Outdated data structure detected.
 * Tracks a CheckoutStarted event specification.
 * ID: 8640a99c-5984-41b3-a5cb-91f8bb5efe90
 */
export function trackCheckoutStartedSpec(checkoutStarted: CheckoutStarted & ContextsOrTimestamp<EcommerceProduct>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '8640a99c-5984-41b3-a5cb-91f8bb5efe90',
        name: 'Checkout Started',
        data_product_id: 'eb003f2a-9b7b-46cf-ad7b-b8f2ee52bef9',
        data_product_name: 'Leo&#x27;s Numismatics Data Product',
        data_product_domain: 'Sales'
    });

    const context = Array.isArray(checkoutStarted.context)
        ? [...checkoutStarted.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCheckoutStarted = {
        ...checkoutStarted,
        context,
    };

    trackCheckoutStarted<EcommerceProduct | EventSpecification>(modifiedCheckoutStarted, trackers);
}
/**
 * Tracks a ProductRemovedFromCart event specification.
 * ID: 9d297939-9166-418f-9bd1-b94de8b13e84
 */
export function trackProductRemovedFromCartSpec(productRemovedFromCart: RemoveFromCart & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '9d297939-9166-418f-9bd1-b94de8b13e84',
        name: 'Product Removed from Cart',
        data_product_id: 'eb003f2a-9b7b-46cf-ad7b-b8f2ee52bef9',
        data_product_name: 'Leo&#x27;s Numismatics Data Product',
        data_product_domain: 'Sales'
    });

    const context = Array.isArray(productRemovedFromCart.context)
        ? [...productRemovedFromCart.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedProductRemovedFromCart = {
        ...productRemovedFromCart,
        context,
    };

    trackRemoveFromCart<Record<string, unknown> | EventSpecification>(modifiedProductRemovedFromCart, trackers);
}


